### ISSUE TITLE
Feature request: Integrate View Transitions API for Smoother Hydration

### ISSUE THREAD

**Issue by kennycallado** [11ty/is-land#37]
Hi!

I'd like to propose integrating the [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API) into is-land using the css [view-transition-name](https://developer.mozilla.org/en-US/docs/Web/CSS/view-transition-name) property.

Currently, when an <is-land> hydrates (especially when using data-island="replace" or when the initialized component modifies the DOM significantly), the visual change can sometimes be abrupt. The View Transitions API provides a powerful, native browser mechanism to create smooth, animated transitions between DOM states.

My suggestion is to introduce a new attribute for the <is-land> element, for example:

```html
<is-land on:visible transition:name="my-component-transition">
    <!-- Initial content or placeholder -->
    <template data-island="replace">
        <!-- Content loaded after hydration -->
    </template>
</is-land>
```

```css
/* Define the animation for the old/new states */
::view-transition-old(my-component-transition) {
  animation: slide-out 0.5s ease-out forwards;
}

::view-transition-new(my-component-transition) {
  animation: slide-in 0.5s ease-in forwards;
}

@keyframes slide-out { /* ... */ }
@keyframes slide-in { /* ... */ }
```

I've already experimented with a potential implementation by modifying the hydrate method to check for the attribute/API support and wrap the DOM updates. It seems feasible and integrates cleanly.

Looking forward to hearing your thoughts!
